import { customType, timestamp, uuid } from "drizzle-orm/pg-core";

/** Case-insensitive text (requires the `citext` extension). Used for email addresses. */
export const citext = customType<{ data: string }>({
  dataType: () => "citext",
});

/** UUID primary key generated by PostgreSQL. IDs in URLs are opaque UUIDs (spec §5). */
export const id = () => uuid("id").primaryKey().defaultRandom();

/** UTC timestamps (spec §16: timestamps are stored in UTC). */
export const timestamps = () => ({
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
