/** Fixed presentation fixture transcribed from Figma 29:1087. Never venture actuals. */
export const GROWTH_FIXTURE = {
  id: "figma-29-1087-v1",
  asOf: "2026-10-05T09:00:00Z",
  currency: "GBP",
  annualRevenue: 61_200_000,
  annualTarget: 100_000_000,
  averageValue: 128_000,
  conversionRate: 0.33,
  inputs: [
    { label: "Leads / month", current: "86", target: "110" },
    { label: "Quote conversion", current: "33%", target: "41%", tone: "warning" },
    { label: "Avg job value", current: "£1,280", target: "£1,420" },
    { label: "Repeat rate", current: "34%", target: "42%" },
    { label: "Team capacity", current: "74%", target: "90%" },
    { label: "Monthly revenue", current: "£51.0k", target: "£83.3k", tone: "revenue" },
  ],
  levers: [
    {
      title: "Raise quote conversion",
      detail: "Follow-up SLA + quote redesign",
      impact: "+£11.8k/mo",
    },
    {
      title: "Unlock team capacity",
      detail: "Hire senior engineer · +32 jobs",
      impact: "+£9.2k/mo",
    },
    {
      title: "Reactivate past customers",
      detail: "240-account service campaign",
      impact: "+£5.4k/mo",
    },
  ],
  actions: [
    {
      title: "Call 12 warm quotes older than 48 hours",
      detail: "Use new two-touch close script · highest-intent pipeline first",
      initials: "SM",
      owner: "Sarah",
      deadline: "Today · 16:00",
      status: "In progress",
      impact: "+£4.8k/mo",
      control: "Continue",
    },
    {
      title: "Publish two-step quote follow-up automation",
      detail: "SMS at 4h · founder call task at 24h",
      initials: "TB",
      owner: "Tom",
      deadline: "Tue · 12:00",
      status: "Ready",
      impact: "+5 conv pts",
      control: "Configure",
    },
    {
      title: "Interview senior engineer shortlist",
      detail: "Three qualified candidates · capacity hire is on critical path",
      initials: "SJ",
      owner: "Sarah + James",
      deadline: "Wed · 15:00",
      status: "Ready",
      impact: "+£9.2k/mo",
      control: "Shortlist",
    },
    {
      title: "Launch 240-customer service reactivation",
      detail: "Boiler service offer · past customers inactive for 12+ months",
      initials: "PS",
      owner: "Priya",
      deadline: "Thu · 10:00",
      status: "Ready",
      impact: "+£5.4k/mo",
      control: "Launch",
    },
    {
      title: "Ring-fence Friday PM for high-value installs",
      detail: "Move low-margin callouts to overflow partner",
      initials: "MB",
      owner: "Marcus",
      deadline: "Fri · 09:00",
      status: "Ready",
      impact: "+£2.1k/wk",
      control: "Schedule",
    },
  ],
} as const;
